# Generated by Django 3.2.8 on 2022-07-24 11:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Muški'), ('Z', 'Ženski'), ('N', 'Ostali')], max_length=1)),
                ('birth_year', models.PositiveIntegerField()),
                ('school_status', models.CharField(choices=[('pohađa', 'Pohađa'), ('prilagođeni program', 'Pohađa po prilagođenom programu'), ('specijalno obrazovanje', 'Pohađa specijalno obrazovanje'), ('ne pohađa', 'Ne pohađa')], max_length=50)),
                ('family_model', models.CharField(choices=[('potpuna porodica', 'Potpuna porodica'), ('nepotpuna porodica', 'Jednoroditeljska/nepotpuna porodica'), ('skrbnici/hranitelji', 'Skrbnici/Hranitelji'), ('institucija', 'Institucija')], max_length=50)),
                ('status', models.BooleanField(choices=[(True, 'Aktivan'), (False, 'Neaktivan')])),
                ('guardian_consent', models.BooleanField(choices=[(True, 'Posjeduje'), (False, 'Ne posjeduje')])),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Developmental_Difficulties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Hang_Out_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mentoring_Reason_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Muški'), ('Z', 'Ženski'), ('N', 'Ostali')], max_length=1)),
                ('birth_year', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '099999999'. Up to 9 digits allowed.", regex='^0[0-9]{8}$')])),
                ('education_level', models.CharField(choices=[('SSSS', 'Srednja skola'), ('BSc', 'Bachelor'), ('MSc', 'Master'), ('Dr', 'Doktor nauka')], max_length=4)),
                ('faculty_department', models.TextField(null=True)),
                ('employment_status', models.CharField(choices=[('zaposlen', 'Zaposlen'), ('nezaposlen', 'Nezaposlen'), ('student', 'Student')], max_length=15)),
                ('good_conduct_certificate', models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')])),
                ('status', models.BooleanField(choices=[(True, 'Aktivan'), (False, 'Neaktivan')])),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.coordinator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer_Organisation_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_city',
            field=models.ManyToManyField(blank=True, related_name='volunteer_city', through='BBBSApp.Volunteer_Organisation_City', to='BBBSApp.City'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_organisation',
            field=models.ManyToManyField(blank=True, related_name='volunteer_organisation', through='BBBSApp.Volunteer_Organisation_City', to='BBBSApp.Organisation'),
        ),
        migrations.CreateModel(
            name='Mentoring_Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.mentoring_reason_category')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
                ('activity_type', models.CharField(choices=[('individualno', 'Individualno'), ('sa drugim parovima', 'Druzenje sa drugim parovima'), ('grupno', 'Grupna aktivnost')], max_length=50)),
                ('evaluation', models.CharField(choices=[(0, 'Lose'), (1, 'Nije lose'), (2, 'Dobro'), (3, 'Super')], max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('activities', models.ManyToManyField(to='BBBSApp.Activities')),
                ('place', models.ManyToManyField(to='BBBSApp.Hang_Out_Place')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator_Organisation_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.coordinator')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='coordinator',
            name='coordinator_city',
            field=models.ManyToManyField(blank=True, related_name='coordinator_city', through='BBBSApp.Coordinator_Organisation_City', to='BBBSApp.City'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='coordinator_organisation',
            field=models.ManyToManyField(blank=True, related_name='coordinator_organisation', through='BBBSApp.Coordinator_Organisation_City', to='BBBSApp.Organisation'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Child_Organisation_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.child')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='child_city',
            field=models.ManyToManyField(related_name='child_organisation', through='BBBSApp.Child_Organisation_City', to='BBBSApp.City'),
        ),
        migrations.AddField(
            model_name='child',
            name='child_organisation',
            field=models.ManyToManyField(related_name='child_organisation', through='BBBSApp.Child_Organisation_City', to='BBBSApp.Organisation'),
        ),
        migrations.AddField(
            model_name='child',
            name='developmental_difficulties',
            field=models.ManyToManyField(to='BBBSApp.Developmental_Difficulties'),
        ),
        migrations.AddField(
            model_name='child',
            name='mentoring_reason',
            field=models.ManyToManyField(to='BBBSApp.Mentoring_Reason'),
        ),
        migrations.AddField(
            model_name='child',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.volunteer'),
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.activity_category'),
        ),
    ]
