# Generated by Django 3.2.8 on 2022-07-04 19:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ManyToManyField(to='BBBSApp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Muški'), ('Z', 'Ženski'), ('N', 'Ostali')], max_length=1)),
                ('birth_year', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '099999999'. Up to 9 digits allowed.", regex='^0[0-9]{8}$')])),
                ('education_level', models.CharField(choices=[('SSSS', 'Srednja skola'), ('BSc', 'Bachelor'), ('MSc', 'Master'), ('Dr', 'Doktor nauka')], max_length=4)),
                ('faculty_department', models.TextField(null=True)),
                ('employment_status', models.CharField(choices=[('zaposlen', 'Zaposlen'), ('nezaposlen', 'Nezaposlen'), ('student', 'Student')], max_length=15)),
                ('good_conduct_certificate', models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')])),
                ('status', models.BooleanField(choices=[(True, 'Aktivan'), (False, 'Neaktivan')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.coordinator')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBBSApp.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coordinator',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BBBSApp.organisation'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('code', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Muški'), ('Z', 'Ženski'), ('N', 'Ostali')], max_length=1)),
                ('birth_year', models.PositiveIntegerField()),
                ('school_status', models.CharField(choices=[('pohađa', 'Pohađa'), ('prilagođeni program', 'Pohađa po prilagođenom programu'), ('specijalno obrazovanje', 'Pohađa specijalno obrazovanje'), ('ne pohađa', 'Ne pohađa')], max_length=50)),
                ('developmental_difficulties', models.TextField()),
                ('family_model', models.CharField(choices=[('potpuna porodica', 'Potpuna porodica'), ('nepotpuna porodica', 'Jednoroditeljska/nepotpuna porodica'), ('skrbnici/hranitelji', 'Skrbnici/Hranitelji'), ('institucija', 'Institucija')], max_length=50)),
                ('mentoring_reason', models.TextField()),
                ('status', models.BooleanField(choices=[(True, 'Aktivan'), (False, 'Neaktivan')])),
                ('guardian_consent', models.BooleanField(choices=[(True, 'Posjeduje'), (False, 'Ne posjeduje')])),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BBBSApp.volunteer')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBBSApp.organisation')),
            ],
        ),
    ]
