# Generated by Django 3.2.8 on 2022-07-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='volunteer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.volunteer'),
        ),
    ]
