# Generated by Django 3.2.8 on 2022-07-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='city',
        ),
        migrations.RemoveField(
            model_name='child',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='organisation',
        ),
        migrations.CreateModel(
            name='Volunteer_Organisation_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator_Organisation_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.coordinator')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Child_Organisation_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.child')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation')),
            ],
        ),
    ]
