# Generated by Django 3.2.8 on 2022-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0002_auto_20220712_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
