# Generated by Django 3.2.8 on 2022-07-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0002_alter_child_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_city',
            field=models.ManyToManyField(related_name='child_city', through='BBBSApp.Child_Organisation_City', to='BBBSApp.City'),
        ),
    ]
