# Generated by Django 3.2.8 on 2022-07-24 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0003_alter_child_child_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.volunteer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birth_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
