# Generated by Django 3.2.8 on 2022-07-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0003_alter_organisation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Developmental_Difficulties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hang_Out_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mentoring_Reason_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='developmental_difficulties',
        ),
        migrations.RemoveField(
            model_name='child',
            name='mentoring_reason',
        ),
        migrations.CreateModel(
            name='Mentoring_Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.mentoring_reason_category')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
                ('activity_type', models.CharField(choices=[('individualno', 'Individualno'), ('sa drugim parovima', 'Druzenje sa drugim parovima'), ('grupno', 'Grupna aktivnost')], max_length=50)),
                ('evaluation', models.CharField(choices=[(0, 'Lose'), (1, 'Nije lose'), (2, 'Dobro'), (3, 'Super')], max_length=50)),
                ('activities', models.ManyToManyField(to='BBBSApp.Activities')),
                ('place', models.ManyToManyField(to='BBBSApp.Hang_Out_Place')),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.activity_category'),
        ),
        migrations.AddField(
            model_name='child',
            name='developmental_difficulties',
            field=models.ManyToManyField(to='BBBSApp.Developmental_Difficulties'),
        ),
        migrations.AddField(
            model_name='child',
            name='mentoring_reason',
            field=models.ManyToManyField(to='BBBSApp.Mentoring_Reason'),
        ),
    ]
