# Generated by Django 3.2.8 on 2022-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0004_auto_20220717_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmental_difficulties',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
