# Generated by Django 3.2.8 on 2024-10-10 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0004_auto_20220724_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '099999999'. Up to 10 digits allowed.", regex=r"^0[0-9]{8,9}$")]),
        ),
    ]
