# Generated by Django 3.2.8 on 2024-12-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0006_auto_20241010_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='code',
            field=models.CharField(max_length=50),
        )
    ]
