# Generated by Django 3.2.8 on 2022-07-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0007_alter_activities_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.coordinator'),
        ),
    ]
