# Generated by Django 3.2.8 on 2022-07-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0008_volunteer_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_city',
            field=models.ManyToManyField(blank=True, related_name='child_organisation', through='BBBSApp.Child_Organisation_City', to='BBBSApp.City'),
        ),
        migrations.AddField(
            model_name='child',
            name='child_organisation',
            field=models.ManyToManyField(blank=True, related_name='child_organisation', through='BBBSApp.Child_Organisation_City', to='BBBSApp.Organisation'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='coordinator_city',
            field=models.ManyToManyField(blank=True, related_name='coordinator_city', through='BBBSApp.Coordinator_Organisation_City', to='BBBSApp.City'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='coordinator_organisation',
            field=models.ManyToManyField(blank=True, related_name='coordinator_organisation', through='BBBSApp.Coordinator_Organisation_City', to='BBBSApp.Organisation'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_city',
            field=models.ManyToManyField(blank=True, related_name='volunteer_city', through='BBBSApp.Volunteer_Organisation_City', to='BBBSApp.City'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_organisation',
            field=models.ManyToManyField(blank=True, related_name='volunteer_organisation', through='BBBSApp.Volunteer_Organisation_City', to='BBBSApp.Organisation'),
        ),
        migrations.AlterField(
            model_name='coordinator_organisation_city',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city'),
        ),
        migrations.AlterField(
            model_name='coordinator_organisation_city',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.coordinator'),
        ),
        migrations.AlterField(
            model_name='coordinator_organisation_city',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation'),
        ),
    ]
