# Generated by Django 3.2.8 on 2022-07-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0009_auto_20220721_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_organisation_city',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.child'),
        ),
        migrations.AlterField(
            model_name='child_organisation_city',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city'),
        ),
        migrations.AlterField(
            model_name='child_organisation_city',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation'),
        ),
        migrations.AlterField(
            model_name='volunteer_organisation_city',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.city'),
        ),
        migrations.AlterField(
            model_name='volunteer_organisation_city',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.organisation'),
        ),
        migrations.AlterField(
            model_name='volunteer_organisation_city',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BBBSApp.volunteer'),
        ),
    ]
