# Generated by Django 3.2.8 on 2022-07-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBBSApp', '0010_auto_20220722_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(default='x', max_length=15),
            preserve_default=False,
        ),
    ]
